name: "build-test"

on: # Rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main
      - "dependency-submission/releases/*"
  push:
    branches:
      - main
      - "dependency-submission/releases/*"

jobs:
  build: # Ensure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install NPM dependencies using pnpm in the 'dependency-submission' directory
      - name: Install NPM dependencies
        working-directory: ./dependency-submission
        run: pnpm install

      # Run all NPM build/test actions in the 'dependency-submission' directory
      - name: Run all NPM build/test actions
        working-directory: ./dependency-submission
        run: pnpm run all
